# Let's extend from the base notebook
# https://github.com/jupyter/docker-stacks/blob/master/base-notebook
 FROM jupyter/base-notebook


 # Install required packages on top of base Jupyter image
 RUN pip install --no-cache \
   numpy \
   pandas \
   scikit-learn \
   seaborn \
   catboost \
   imblearn


 # Copy all files (current directory onwards) into the image
 COPY yelp_dataset ./yelp_dataset
 COPY Yelp_data_analysis.ipynb ./Yelp_data_analysis.ipynb
 